version: '2.0'

services:
  backend:
    build: docker/node
    links:
      - mongo
    volumes:
      - ./backend:/code:rw
      - ./results/subevents.js:/code/subevents.js:rw
      - ./results/subeventresults.js:/code/subeventresults.js:rw
    command: sh -c 'cd /code; npm install; npm run dev'
    ports:
      - 8090:8090
  mongo:
    image: mongo

  front-dev:
    build: docker/node
    command: sh -c 'cd /front; npm install; npm run serve'
    volumes:
    - ./front/:/front:rw
    - ./results/subevents.js:/front/src/config/subevents.js:rw
    ports:
    - 8080:8080
